import { AppDefinition } from '../types/app';
import { Notepad } from '../components/apps/Notepad/Notepad';
import { Calculator } from '../components/apps/Calculator/Calculator';
import { FileExplorer } from '../components/apps/FileExplorer/FileExplorer';
import { Settings } from '../components/apps/Settings/Settings';
import { PresentationApp } from '../components/apps/Presentation/PresentationApp';
import { Presentation2App } from '../components/apps/Presentation2/Presentation2App';
import { Terminal } from '../components/apps/Terminal/Terminal';
import { Snake } from '../components/apps/games/Snake/Snake';
import { Tetris } from '../components/apps/games/Tetris/Tetris';
import { BrickBreaker } from '../components/apps/games/BrickBreaker/BrickBreaker';
import { Doom } from '../components/apps/games/Doom/Doom';
import { FlappyBird } from '../components/apps/games/FlappyBird/FlappyBird';
import { GamesFolder } from '../components/apps/GamesFolder/GamesFolder';
import { Spreadsheet } from '../components/apps/Spreadsheet/Spreadsheet';
import { ImageViewer } from '../components/apps/ImageViewer/ImageViewer';
import { MediaPlayer } from '../components/apps/MediaPlayer/MediaPlayer';
import PresentationsPanel from '../components/PresentationsPanel/PresentationsPanel';
import { RecycleBin } from '../components/apps/RecycleBin/RecycleBin';

export const APP_REGISTRY: Record<string, AppDefinition> = {
  'file-explorer': {
    id: 'file-explorer',
    name: 'File Explorer',
    icon: '📁',
    component: FileExplorer,
    defaultWidth: 900,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 300,
    singleton: true,
    tileSize: 'medium',
  },
  'notepad': {
    id: 'notepad',
    name: 'Notepad',
    icon: '📝',
    component: Notepad,
    defaultWidth: 650,
    defaultHeight: 450,
    minWidth: 300,
    minHeight: 200,
    singleton: false,
    tileSize: 'small',
  },
  'calculator': {
    id: 'calculator',
    name: 'Calculator',
    icon: '🧮',
    component: Calculator,
    defaultWidth: 320,
    defaultHeight: 500,
    minWidth: 280,
    minHeight: 400,
    singleton: true,
    tileSize: 'small',
  },
  'settings': {
    id: 'settings',
    name: 'Settings',
    icon: '⚙️',
    component: Settings,
    defaultWidth: 900,
    defaultHeight: 600,
    minWidth: 500,
    minHeight: 400,
    singleton: true,
    tileSize: 'medium',
  },
  'presentation': {
    id: 'presentation',
    name: 'AI Tools Setup',
    icon: '🧠',
    component: PresentationApp,
    defaultWidth: 960,
    defaultHeight: 640,
    minWidth: 500,
    minHeight: 380,
    singleton: true,
    tileSize: 'wide',
  },
  'presentation2': {
    id: 'presentation2',
    name: 'AI Models & Tracking',
    icon: '🧠',
    component: Presentation2App,
    defaultWidth: 960,
    defaultHeight: 640,
    minWidth: 500,
    minHeight: 380,
    singleton: true,
    tileSize: 'wide',
  },
  'terminal': {
    id: 'terminal',
    name: 'Terminal',
    icon: '💻',
    component: Terminal,
    defaultWidth: 800,
    defaultHeight: 500,
    minWidth: 400,
    minHeight: 250,
    singleton: false,
    tileSize: 'medium',
  },
  'snake': {
    id: 'snake',
    name: 'Snake',
    icon: '🐍',
    component: Snake,
    defaultWidth: 500,
    defaultHeight: 540,
    minWidth: 360,
    minHeight: 400,
    singleton: true,
    tileSize: 'small',
  },
  'tetris': {
    id: 'tetris',
    name: 'Tetris',
    icon: '🧱',
    component: Tetris,
    defaultWidth: 500,
    defaultHeight: 680,
    minWidth: 380,
    minHeight: 500,
    singleton: true,
    tileSize: 'small',
  },
  'brick-breaker': {
    id: 'brick-breaker',
    name: 'Brick Breaker',
    icon: '🏓',
    component: BrickBreaker,
    defaultWidth: 520,
    defaultHeight: 620,
    minWidth: 400,
    minHeight: 500,
    singleton: true,
    tileSize: 'small',
  },
  'doom': {
    id: 'doom',
    name: 'DOOM',
    icon: '💀',
    component: Doom,
    defaultWidth: 800,
    defaultHeight: 600,
    minWidth: 640,
    minHeight: 480,
    singleton: true,
    tileSize: 'medium',
  },
  'flappy-bird': {
    id: 'flappy-bird',
    name: 'Flappy Bird',
    icon: '🐤',
    component: FlappyBird,
    defaultWidth: 420,
    defaultHeight: 600,
    minWidth: 320,
    minHeight: 450,
    singleton: true,
    tileSize: 'small',
  },
  'games': {
    id: 'games',
    name: 'Games',
    icon: '📁',
    component: GamesFolder,
    defaultWidth: 900,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 300,
    singleton: true,
    tileSize: 'medium',
  },
  'spreadsheet': {
    id: 'spreadsheet',
    name: 'Spreadsheet',
    icon: '📊',
    component: Spreadsheet,
    defaultWidth: 700,
    defaultHeight: 450,
    minWidth: 400,
    minHeight: 300,
    singleton: false,
    tileSize: 'small',
  },
  'image-viewer': {
    id: 'image-viewer',
    name: 'Photos',
    icon: '🖼️',
    component: ImageViewer,
    defaultWidth: 600,
    defaultHeight: 500,
    minWidth: 300,
    minHeight: 250,
    singleton: false,
    tileSize: 'small',
  },
  'media-player': {
    id: 'media-player',
    name: 'Media Player',
    icon: '🎬',
    component: MediaPlayer,
    defaultWidth: 600,
    defaultHeight: 450,
    minWidth: 350,
    minHeight: 300,
    singleton: false,
    tileSize: 'small',
  },
  'lessons': {
    id: 'lessons',
    name: 'Lessons',
    icon: '📂',
    component: PresentationsPanel,
    defaultWidth: 900,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 300,
    singleton: true,
    tileSize: 'medium',
  },
  'recycle-bin': {
    id: 'recycle-bin',
    name: 'Recycle Bin',
    icon: '🗑️',
    component: RecycleBin,
    defaultWidth: 900,
    defaultHeight: 600,
    minWidth: 400,
    minHeight: 300,
    singleton: true,
    tileSize: 'medium',
  },
};
